### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Emkayxd** [anggaxd/ambf#2]
**Termux** isn't working please i need solution🙏
My country is **Nigeria** @anggaxd

**Comment by anggaxd** [comment]
Yes this work in your contry

**Comment by Emkayxd** [comment]
It was working but suddenly stops giving result
10k friends with 2 result or non

**Comment by anggaxd** [comment]
> 

try use method mbasic 
my paypal : paypal.me/garzxd
