### ISSUE TITLE
Let's talk on WhatsApp🙏🙏🙏

### ISSUE THREAD

**Issue by Emkayxd** [anggaxd/ambf#3]
http://wa.me/2349036900819

Bro i seriously need your help, please message me on WhatsApp, if you help me I'll pay you😪
Not trying to buy you but i just need help

**Comment by Krish-bhardwaj** [comment]
Hi what is your issue can u explain i would like to contribute

**Comment by Emkayxd** [comment]
> Hi what is your issue can u explain i would like to contribute 

Good morning from (Nigeria) 
I have been using this tool and other tools for more than a year now, and earlier this week (Sunday) it stopped giving results😪![Screenshot_20220113-072833.jpg](https://user-images.githubusercontent.com/89442462/149277450-35ffa54d-27a0-4a76-99e9-900479e3f798.jpg)

**Comment by Krish-bhardwaj** [comment]
have u tried reinstalling this app

**Comment by Emkayxd** [comment]
Yes uninstalled 3 times

**Comment by Krish-bhardwaj** [comment]
sorry i am not able to get your problem i am not an expert😔

**Comment by Emkayxd** [comment]
> sorry i am not able to get your problem i am not an expert😔

Ok bro

**Comment by Emkayxd** [comment]
> sorry i am not able to get your problem i am not an expert😔

You also hack right?
Let's talk on WhatsApp

**Comment by Krish-bhardwaj** [comment]
> > sorry i am not able to get your problem i am not an expert😔
> 
> You also hack right? Let's talk on WhatsApp
no i am just a biggner developer
